-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.aluno
(
    codigo bigserial NOT NULL,
    nome text,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public.nota
(
    codigo bigserial NOT NULL,
    valor numeric(5, 2),
    codigo_aluno bigint,
    codigo_prova bigint,
    PRIMARY KEY (codigo)
);

CREATE TABLE IF NOT EXISTS public.prova
(
    codigo bigserial NOT NULL,
    descricao text,
    materia text,
    data date,
    PRIMARY KEY (codigo)
);

ALTER TABLE public.nota
    ADD FOREIGN KEY (codigo_aluno)
    REFERENCES public.aluno (codigo)
    NOT VALID;


ALTER TABLE public.nota
    ADD FOREIGN KEY (codigo_prova)
    REFERENCES public.prova (codigo)
    NOT VALID;

END;